import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Login': 'Login',
          'Username': 'Username',
          'Password': 'Password',
          'Change Language': 'Change Language',
          'Welcome to BP Survey': 'Welcome to BP Survey',
          'Username is required': 'Username is required',
          'Password is required': 'Password is required',
          'Password must be at least 6 characters': 'Password must be at least 6 characters',
          'New Survey': 'New Survey',
          'Completed Surveys': 'Completed Surveys',
          'Good Morning': 'Good Morning',
          'APSCO Survey': 'APSCO Survey',
          'No questions available': 'No questions available',
          'Submit Survey': 'Submit Survey',
          'Enter your answer': 'Enter your answer',
          'Completed': 'Completed',
          'Total': 'Total',
          'Previous': 'Previous',
          'Next': 'Next',
          'Submit': 'Submit',
          'Survey submitted successfully': 'Survey submitted successfully',
          'Please specify': 'Please specify',
          'Location permission is required to start a survey.': 'Location permission is required to start a survey.',
          'Location services are disabled. Please enable GPS.': 'Location services are disabled. Please enable GPS.',
          'Location permission denied.': 'Location permission denied.',
          'Location permissions are permanently denied. Please enable them in settings.': 'Location permissions are permanently denied. Please enable them in settings.',
          'Could not retrieve location. Please try again.': 'Could not retrieve location. Please try again.',
          'Enter numeric value': 'Enter numeric value',
          'Location Required': 'Location Required',
          'Success': 'Success',
          'Error': 'Error',
          'User session expired': 'User session expired',
          'Exit Survey': 'Exit Survey',
          'Are you sure you want to exit? Your progress will be lost.': 'Are you sure you want to exit? Your progress will be lost.',
          'Are you sure you want to submit your answers?': 'Are you sure you want to submit your answers?',
          'Cancel': 'Cancel',
          'Yes': 'Yes',
          'No': 'No',
          'Survey Submitted Successfully': 'Survey Submitted Successfully',
        },
        'ar': {
          'Login': 'تسجيل الدخول',
          'Username': 'اسم المستخدم',
          'Password': 'كلمة المرور',
          'Change Language': 'تغيير اللغة',
          'Welcome to BP Survey': 'مرحباً بكم في BP Survey',
          'Username is required': 'اسم المستخدم مطلوب',
          'Password is required': 'كلمة المرور مطلوبة',
          'Password must be at least 6 characters': 'كلمة المرور يجب أن تكون ٦ أحرف على الأقل',
          'New Survey': 'استبيان جديد',
          'Completed Surveys': 'الاستبيانات المكتملة',
          'Good Morning': 'صباح الخير',
          'APSCO Survey': 'استبيان APSCO',
          'No questions available': 'لا توجد أسئلة متاحة',
          'Submit Survey': 'إرسال الاستبيان',
          'Enter your answer': 'أدخل إجابتك',
          'Completed': 'المكتملة',
          'Total': 'الإجمالي',
          'Previous': 'السابق',
          'Next': 'التالي',
          'Submit': 'إرسال',
          'Survey submitted successfully': 'تم إرسال الاستبيان بنجاح',
          'Please specify': 'يرجى التحديد',
          'Location permission is required to start a survey.': 'مطلوب إذن الموقع لبدء الاستبيان.',
          'Location services are disabled. Please enable GPS.': 'خدمات الموقع معطلة. يرجى تفعيل نظام تحديد المواقع (GPS).',
          'Location permission denied.': 'تم رفض إذن الموقع.',
          'Location permissions are permanently denied. Please enable them in settings.': 'أذونات الموقع مرفوضة نهائياً. يرجى تفعيلها من الإعدادات.',
          'Could not retrieve location. Please try again.': 'تعذر الحصول على الموقع. يرجى المحاولة مرة أخرى.',
          'Enter numeric value': 'أدخل قيمة عددية',
          'Location Required': 'الموقع مطلوب',
          'Success': 'نجاح',
          'Error': 'خطأ',
          'User session expired': 'انتهت جلسة المستخدم',
          'Exit Survey': 'الخروج من الاستبيان',
          'Are you sure you want to exit? Your progress will be lost.': 'هل أنت متأكد أنك تريد الخروج؟ سيتم فقدان تقدمك.',
          'Are you sure you want to submit your answers?': 'هل أنت متأكد أنك تريد إرسال إجاباتك؟',
          'Cancel': 'إلغاء',
          'Yes': 'نعم',
          'No': 'لا',
          'Survey Submitted Successfully': "تم إرسال الاستبيان بنجاح"
        }
      };
}
